id: A4A1DA05A
title: Verses of Homage to the Buddhas and Bodhisattvas Together with their Mantras
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:12:12.055998
  last_modified_at: 2022-03-01 05:12:12.056001
