id: A4A1DA05A
title: 'The Swift Infusion of Blessings: In Praise of Mañjughoṣa'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:12:12.047448
  last_modified_at: 2022-03-01 05:12:12.047451
