id: A4A1DA05A
title: 'In Praise of Mañjuśrī: Increasing Intelligence to the Full'
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:12:11.987787
  last_modified_at: 2022-03-01 05:12:11.987790
