id: A4A1DA05A
title: Verses in Praise of the Protector Akṣobhya
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:12:12.052650
  last_modified_at: 2022-03-01 05:12:12.052653
