id: A4A1DA05A
title: 'The Sweet Sound of Perfect Joy: In Praise of the Goddess Sarasvatī'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:12:12.045774
  last_modified_at: 2022-03-01 05:12:12.045778
