id: A4A1DA05A
title: Praise of Kunga Yeshe, Great Being and Master of Extensive Scriptural Traditions
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:12:12.001249
  last_modified_at: 2022-03-01 05:12:12.001252
