id: A4A1DA05A
title: 'Thunderous Melody: In Praise of the Omniscient Gorampa Sonam Senge'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:12:12.051257
  last_modified_at: 2022-03-01 05:12:12.051259
