id: A4A1DA05A
title: 'Gentle Splendour: Praises to the Great Abbot Śāntarakṣita'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:12:11.979776
  last_modified_at: 2022-03-01 05:12:11.979784
