id: A4A1DA05A
title: 'Praise of the Buddha: With Skilful Means & Compassion...'
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:12:12.005943
  last_modified_at: 2022-03-01 05:12:12.005946
