id: A4A1DA05A
title: 'The Purifier of Ethical Discipline: An Aspirational Praise to Vajradhara Kunga
  Zangpo'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:12:12.039361
  last_modified_at: 2022-03-01 05:12:12.039364
