id: A4A1DA05A
title: In Praise of Patrul Orgyen Jigme Chökyi Wangpo
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:12:11.992057
  last_modified_at: 2022-03-01 05:12:11.992061
