id: A4A1DA05A
title: 'The Bestowal of Supreme Blessings: Praise to the Vajradhara Loter Wangpo'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:12:12.023911
  last_modified_at: 2022-03-01 05:12:12.023914
