id: A4A1DA05A
title: In Praise of the Three Jewels
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:12:11.997775
  last_modified_at: 2022-03-01 05:12:11.997778
