id: A4A1DA05A
title: 'The Excellent Bilva Tree of Auspiciousness: Praise and Prayer to Terchen Chokgyur
  Lingpa'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:12:12.026152
  last_modified_at: 2022-03-01 05:12:12.026155
