id: A4A1DA05A
title: 'Sweet Melody to Delight the Glorious Deity: In Praise of Śrī Kālīdevī'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:12:12.021520
  last_modified_at: 2022-03-01 05:12:12.021523
