id: A4A1DA05A
title: 'The Fulfilment of All Aspirations: In Praise of Noble Tārā'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:12:12.028451
  last_modified_at: 2022-03-01 05:12:12.028454
