id: A4A1DA05A
title: 'Ripples on the Ganges: In Praise of the Goddess Sarasvatī'
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:12:12.010883
  last_modified_at: 2022-03-01 05:12:12.010886
