id: A4A1DA05A
title: In Praise of the Goddess Mārīcī (Özerchenma)
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:12:11.995231
  last_modified_at: 2022-03-01 05:12:11.995234
