id: A4A1DA05A
title: 'The Three Kāyas: Praises to the Great Master Padmasambhava'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:12:12.049765
  last_modified_at: 2022-03-01 05:12:12.049768
