id: A4A1DA05A
title: 'The Staircase Ascending to Khecara: A Praise in Accord with the Arrangement
  of the Realm of Holy Nāro Khecarī'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:12:12.041434
  last_modified_at: 2022-03-01 05:12:12.041437
