id: A4A1DA05A
title: Praise of Noble Avalokiteśvara
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:12:12.002563
  last_modified_at: 2022-03-01 05:12:12.002566
