id: A4A1DA05A
title: A Song of Innermost Praise to Vajrasattva
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:12:11.969964
  last_modified_at: 2022-03-01 05:12:11.969968
