id: A4A1DA05A
title: 'The Hero''s Bellowing Laughter: In Praise of the Lord of Yogins'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:12:12.029772
  last_modified_at: 2022-03-01 05:12:12.029775
