id: A4A1DA05A
title: 'Fully Blossomed Learning and Contemplation: A Praise of the Great Spiritual
  Friend Jamyang Gyaltsen'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:12:11.976747
  last_modified_at: 2022-03-01 05:12:11.976752
