id: A4A1DA05A
title: 'Beautiful Adornment of the Earth: In Praise of Kṣitigarbha'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:12:11.971870
  last_modified_at: 2022-03-01 05:12:11.971873
