id: A4A1DA05A
title: 'Music to Delight the Ḍākinī: A Praise to the Deathless Mandāravā'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:12:11.999765
  last_modified_at: 2022-03-01 05:12:11.999768
